# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hiemanshu Sharma
email: hello@hiems.net
description: >- # this means to ignore newlines until "baseurl:"
  Hiemanshu Sharma is a software engineer working on developing
  progressive tech helping orgs build the tools they need to
  work on digital campaigning and progressive change.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hiems.net" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  hiemanshu

plugins:
  - jekyll-feed

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
